"""Render a Report as a colored terminal summary or a Markdown audit document."""
from __future__ import annotations

from .model import Report, Severity

# ASCII markers only - a CLI tool must not crash on a Windows cp1252 console
_ICON = {Severity.OK: "[ok]", Severity.INFO: "[..]", Severity.WARN: "[WARN]", Severity.FAIL: "[FAIL]"}


def to_text(report: Report) -> str:
    c = report.counts()
    lines = [f"mcp-probe report - {report.server}",
             f"tools: {len(report.tools)}   score: {report.score()}/100  (grade {report.grade()})",
             f"ok={c['ok']}  info={c['info']}  warn={c['warn']}  fail={c['fail']}", ""]
    by_tool: dict[str, list] = {}
    for f in report.findings:
        by_tool.setdefault(f.tool, []).append(f)
    for tool, findings in by_tool.items():
        lines.append(f"[{tool}]")
        for f in findings:
            if f.severity is Severity.OK:
                continue
            lines.append(f"  {_ICON[f.severity]} {f.check}: {f.message}")
        oks = sum(1 for f in findings if f.severity is Severity.OK)
        if oks:
            lines.append(f"  [ok] {oks} checks passed")
        lines.append("")
    return "\n".join(lines)


def to_markdown(report: Report) -> str:
    c = report.counts()
    out = [f"# MCP audit - `{report.server}`", "",
           f"**Score: {report.score()}/100 (grade {report.grade()})** · "
           f"{len(report.tools)} tools · "
           f"{c['fail']} fail / {c['warn']} warn / {c['info']} info / {c['ok']} ok", "",
           "| Tool | Check | Severity | Detail |", "|---|---|---|---|"]
    for f in report.findings:
        if f.severity is Severity.OK:
            continue
        out.append(f"| `{f.tool}` | {f.check} | **{f.severity.value}** | {f.message} |")
    if all(f.severity is Severity.OK for f in report.findings):
        out.append("| - | - | ok | No warnings or failures. |")
    out += ["", "## Tools discovered", ""]
    for t in report.tools:
        out.append(f"- **`{t.name}`** - {t.description or '_(no description)_'} "
                   f"({len(t.properties)} params, {len(t.required)} required)")
    out += ["", "---", "_Generated by [mcp-probe](https://github.com/junaidshahid-dev/mcp-probe)._"]
    return "\n".join(out)
